### ISSUE TITLE
Attendees doesn't appear 

### ISSUE THREAD

**Issue by winnertako** [texxasrulez/Caldav_Calendar#40] opened 2019-11-07 11:20 UTC
Hello, 

For some reason when I add attendees for my events the participants receive the email notifications but doesn't show up on details of event. And then if I click on event the popup doesn't' appear.

Any idea what is causing this?

Thank you.

**Comment by texxasrulez** [comment] 2019-11-09 08:17
I cannot recreate. Please give as detailed description as you can. Server, database, log entries, etc ...

**Comment by winnertako** [comment] 2019-11-09 12:04
I'm running Roundcube Webmail 1.3.8 and  I'm using your plugin to connect with the Davical 1.1.8 and everything works like expected  but I have this problem with events creation.

I don't have any error on my logs. For example I've created two events for **testing** and **AA** with attendees invited. The attendees received the invite but in some cases they doesn't appear on my view. 

On my database entries I noticed when the events are created with the Caldav_Calendar,  the attendees column are empty. 
`select title, attendees, start from caldav_events  where calendar_id = '8';`
-  **Test new Caldav** have been created on thunderbird side
`| IT Team: bi-weekly Team Meeting                  | [{"name":"Pa","email":"pa@domain.com","role":"ORGANIZER","status":"ACCEPTED"},{"name":"Rs","status":"ACCEPTED","role":"REQ-PARTICIPANT","cutype":"INDIVIDUAL","rsvp":true,"email":"rs@domain.com"},{"name":"na@domain.com","status":"NEEDS-ACTION","role":"REQ-PARTICIPANT","cutype":"INDIVIDUAL","rsvp":true,"email":"na@domain.com"},{"name":"Fa","status":"ACCEPTED","role":"REQ-PARTICIPANT","cutype":"INDIVIDUAL","rsvp":true,"email":"fa@domain.com"}] | 2040-01-03 09:30:00 |`

-  **testing** have been created with Caldav_Calendar with user not present on my ldap

`| testing                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | 2019-11-09 13:30:00 |`

-  **AA** have been created with Caldav_Calendar with a user present on my ldap
`| AA                                               | [{"email":"na@domain.com","name":"Na","role":"REQ-PARTICIPANT","status":"NEEDS-ACTION","cutype":"INDIVIDUAL","rsvp":true}]                                                                                                                                                                                                                                                                                                                                                                                                                           | 2019-11-09 16:30:00 |
`

My logs:
```
tailf /var/www/html/roundcube/logs/console
[09-Nov-2019 11:33:01 +0000]: <hrhiui7e> caldav_driver: Push new event to url /caldav.php/user/calendar/047E3399DF5CA859E06D9193D74F9B4A-E9ED345EFB99FB84.ics
[09-Nov-2019 11:33:13 +0000]: <hrhiui7e> caldav_driver: Ctag indicates that calendar "8" needs update!
[09-Nov-2019 11:33:13 +0000]: <hrhiui7e> caldav_driver: Calendar "8" needs update.
[09-Nov-2019 11:33:13 +0000]: <hrhiui7e> caldav_driver: Syncing calendar id "8".
[09-Nov-2019 11:49:31 +0000]: <hrhiui7e> caldav_driver: Push new event to url /caldav.php/fsousa/calendar/0DDE60AE2D15B410720F067918050B29-E9ED345EFB99FB84.ics
[09-Nov-2019 11:50:13 +0000]: <hrhiui7e> caldav_driver: Ctag indicates that calendar "8" needs update!
[09-Nov-2019 11:50:13 +0000]: <hrhiui7e> caldav_driver: Calendar "8" needs update.
[09-Nov-2019 11:50:13 +0000]: <hrhiui7e> caldav_driver: Syncing calendar id "8".
[09-Nov-2019 11:50:14 +0000]: <hrhiui7e> caldav_driver: Event 0DDE60AE2D15B410720F067918050B29-E9ED345EFB99FB84 needs update.
```

My web view:

![Screenshot from 2019-11-09 11-50-29](https://user-images.githubusercontent.com/52783790/68528211-abb9c180-02e7-11ea-8a71-e98e36d48536.png)
![Screenshot from 2019-11-09 11-50-43](https://user-images.githubusercontent.com/52783790/68528214-afe5df00-02e7-11ea-82c7-46f36611250a.png)

**Comment by winnertako** [comment] 2019-11-09 13:43
I noticed a little difference on attendees column when a invite are create with Thunderbird or with roundcube plugin

**Thunderbird**
```
MariaDB [roundcube]> select attendees from caldav_events where title = 'crlx';
Empty set (0.01 sec)

MariaDB [roundcube]> 
MariaDB [roundcube]> select attendees from caldav_events where title = 'crlx';
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| attendees                                                                                                                                                                                                                    |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [{"status":"ACCEPTED","role":"ORGANIZER","rsvp":true,"email":"userX@domain.com"},{"name":"Nuno Oliveira","status":"NEEDS-ACTION","role":"REQ-PARTICIPANT","rsvp":true,"email":"userY@domain.com"}] |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Roundcube**
```
MariaDB [roundcube]> select attendees from caldav_events where title = 'crls';
+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| attendees                                                                                                                                              |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| [{"email":"userY@domain.com","name":"Nuno Oliveira","role":"REQ-PARTICIPANT","status":"NEEDS-ACTION","cutype":"INDIVIDUAL","rsvp":true}] |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

**Comment by winnertako** [comment] 2019-11-19 14:45
Hello, 

Any idea why the organizer is not present on database when the event is created with the plugin?

Thank you.

**Comment by winnertako** [comment] 2019-11-21 16:33
Hello, 

I found another weird behavior... So when I add a new event the participants receive the email notifications but doesn't show up on details of event. 

At this time I've the value on database but if I synchronize my calendar  on Thunderbird or Evolution my column attendees became empty value :(

**Comment by texxasrulez** [comment] 2019-12-01 23:56
Give me a bit. I am going through a pretty comprehensive code review. I am hoping to have new features and other fixes. Thanks

**Comment by texxasrulez** [comment] 2019-12-06 05:46
Download latest update. Will close issue in a few days if no report

**Comment by winnertako** [comment] 2019-12-06 14:55
I'm not able to test it because I have several error messages like this #44  and #22

**Comment by winnertako** [comment] 2019-12-08 12:50
Hello,  
After the updade the problem with attendees persist :( they doesn't appear when an event are created

**Comment by texxasrulez** [comment] 2019-12-09 00:36
I honestly cannot reproduce this. Attached are my screenshots ... 

![participants](https://user-images.githubusercontent.com/10519182/70399409-b051c280-19d8-11ea-80c9-cba350ce7e38.png)
![participants-edit](https://user-images.githubusercontent.com/10519182/70399410-b0ea5900-19d8-11ea-8e47-e45c6ef95300.png)


What plugins are you using? Do you have any errors in your RC log or system log?
I am trying to help out here, but unless I am misunderstanding, it is working as expected for me.

**Comment by texxasrulez** [comment] 2019-12-29 23:05
Since no reply and I cannot recreate this, I am closing issue.

**Closed by texxasrulez** 2019-12-29 23:05 UTC
