### ISSUE TITLE
Enhancement request: Allow different logins for roundcube and nextcloud.

### ISSUE THREAD

**Issue by manfredu** [texxasrulez/Caldav_Calendar#51] opened 2020-01-10 12:00 UTC
Is there a way to work around the limitation: "Your username and password must be the same for Nextcloud and Roundcube to work properly."?

I would like to use this plugin but can't make my passwords match.

**Comment by texxasrulez** [comment] 2020-01-24 04:30
Authentication is pretty complex and I do not have the time or skills to reinvent the wheel. On a side note, why can you not make the passwords match? I advise my users to create their Nextcloud account using their email address as their login and the exact password they use for their email accounts as their password. No issues at all. Easy as Pie. 

If you can give a little more detail in why your are experiencing your issue, or maybe what you are trying to accomplish, it may help. Remember, the more detailed information you can provide, the easier it is to come up with a resolution. Log files, OS info, etc ...

**Comment by manfredu** [comment] 2020-01-24 06:53
Nextcloud and Rouncube reside on the same server, whereas the imap server is completely separate with different rules. But if there is no easy solution for you I will try to align this long-term.

**Comment by texxasrulez** [comment] 2020-01-24 07:24
It should not matter where your imap server is. An email address and password are the same all over. I am sorry but I do not know what you mean my "different rules". I am closing this issue in 24 hours if you cannot provide specifics previously requested and EXACT steps to reproduce your issue.

**Comment by manfredu** [comment] 2020-01-24 07:40
Nextcloud uses the email address as user name and imap uses the local user from the system where it resides for autentication and it stores the mails inside the user home directory (e.g. /home/manfred/Maildir).

**Comment by texxasrulez** [comment] 2020-01-24 08:10
This plugin uses a database of the user details for logins, just like Nextcloud and email servers. What you are describing makes no sense to me. Email home directories have no part in this. That is just where emails are stored, no authentication is stored or originates from there.

Again, I ask for detailed logs, screen captures and specifics. Particularly in your case, what email server software is used on your server and what does it's logs say? I need to know specifics. I am sorry to repeat myself, but I cannot help without it ...

**Comment by texxasrulez** [comment] 2020-01-30 06:31
Upon thinking a little more on this, this plugin uses %u from Roundcube, which is the parameter used by Roundcube to login to your imap server, so instead of creating usernames within Nextcloud using full email addresses, use what your imap wants to use as the login for Nextcloud. I assume your imap is using the email address with the "@whateverdomain.com" stripped, so using just the first part of your email address should work ....

**Comment by texxasrulez** [comment] 2020-01-31 11:22
@manfredu I am going to close this as an issue since you did post it as an Enhancement. I have added to my wishlist and will work on this in the future. I do thank you for your interest and hope you have a great weekend ...

**Closed by texxasrulez** 2020-01-31 11:22 UTC
